### ISSUE TITLE
USER STORY: Learn about stress

### ISSUE THREAD

**Issue by andersganander** [andersganander/2406-hackathon-team3#3]
EPIC <epic>

As a **user** I want to **understand what stress is and it's effects on the body and mind** so that **i can better recognize and manage my own stress levels**

**Acceptance criteria**

- [x] A web page with
- [x]   Information about the definition of stress
- [x]   Articles explaining the biological and psychological aspects of stress 

**Tasks**
- [ ] Design and implement a web page with a background image and some stress related articles

**Comment by Christina5P** [comment]
Here is a suggestion of test for a texture:


### Understanding Stress
Stress is a response that begins in the mind, shaped by our reactions to external situations and our capacity to manage these reactions. 
Mental stress, in particular, arises from how we perceive expectations and demands and our ability to cope with them.
Stress can be both beneficial and detrimental. 
Experiencing both positive and negative stress is a normal part of life
Positive stress can be beneficial, helping to boost productivity and provide stimulation, preventing boredom and isolation.
Nonetheless, it is crucial to ensure periods of recovery and rest, even with positive stress.
Without proper rest, the body may exhibit physical symptoms as a reaction to sustained stress.

 **Stress factors come from different factors, as:**
* Work-related pressures
* Financial problems
* Major life changes
* Relationship issues

**You can also experience stress from:**
* Personal attitudes
* Beliefs
* Expectations
* Perceptions
As you see, there are things you can practice and process with your internal factors to help you handle stress.
By understanding the different facets of stress, you can create effective management strategies and navigate stress to maintain your overall well-being.
And it´s important to be aware of that before you get pain from chronic stress, physical issues or mental health disorders.
