### ISSUE TITLE
USER STORY: Asses my stress levels

### ISSUE THREAD

**Issue by andersganander** [andersganander/2406-hackathon-team3#4]
EPIC <epic>

As a **user** I want to **take a self-assessment quiz** so that **i can identify my current stress level and understand my stressors**

**Acceptance criteria**

- [ ] A page with a form consisting of different types of stress (e.g., general, work-related, financial)
- [ ] Immediate feedback and scoring after filling in the form
- [ ] Suggestions for articles or resources based on quiz results

**Tasks**

- [x] Design the layout of the quiz page
- [x] Design the quiz questions
- [x] #21
- [x]    Selecting and presenting questions
- [x] #23
- [x] #22
